### ISSUE TITLE
Proposal: use an entrypoint

### ISSUE THREAD

**Issue by evantill** [commitizen-tools/commitizen-docker-image#12]
Hi,

Thank you for this docker image 👍.
 
Using an `ENTRYPOINT` when wrapping a cli tool using a docker image ease the use of the image

Example of an article that will explain it better than me https://spin.atomicobject.com/2015/11/30/command-line-tools-docker/

By using an ENTRYPOINT, all of the arguments to docker run following our image name are passed as arguments to our application.

I will be happy to make a PR if you agrre with this proposal.

 Please let me know if you have any questions or concerns about this proposal.

**Comment by woile** [comment]
Sure, go ahead. Thanks

**Comment by evantill** [comment]
it will break the v2 convention. Maybe a goot idea to increase the major version

For example in the workflow :

https://github.com/commitizen-tools/commitizen-docker-image/blob/601902c6614ee69f4940cf074d24dd157b927aff/.github/workflows/publish-container.yml#L52

**Comment by evantill** [comment]
In script/build:
https://github.com/commitizen-tools/commitizen-docker-image/blob/601902c6614ee69f4940cf074d24dd157b927aff/scripts/build#L8

In scripts/run:
https://github.com/commitizen-tools/commitizen-docker-image/blob/601902c6614ee69f4940cf074d24dd157b927aff/scripts/run#L2

**Comment by evantill** [comment]
And in the readme:

https://github.com/commitizen-tools/commitizen-docker-image/blob/601902c6614ee69f4940cf074d24dd157b927aff/README.md?plain=1#L11-L17

**Comment by woile** [comment]
It would break it in what way? The way it's used?

**Comment by evantill** [comment]
Yes in the way it is used

Before:
```bash
docker run --rm -v $(pwd):/app commitizen/commitizen:latest /bin/sh -c 'cz bump --changelog'
```

After:
```bash
docker run --rm -v $(pwd):/app commitizen/commitizen:latest bump --changelog
```

**Comment by evantill** [comment]
That why I propose to update the ~~main~~ master branch for a V3 release.

**Comment by evantill** [comment]
I see 2 options here: 

1. Update V2 references to V3 in the code
2. Remove hardcoded references to the version

**Comment by woile** [comment]
This is the way now
