### ISSUE TITLE
[Outdated cz image] The current docker image commitizen-tools/commitizen is outdated

### ISSUE THREAD

**Issue by ranimufid** [commitizen-tools/commitizen-docker-image#7]
The current `cz` docker image is outdated and at version `2.4.0`. 

It also seems that version isn't backwards compatible with the latest `2.17.9` version resulting in 

```
+ cz bump --changelog
[NO_VERSION_SPECIFIED]
Check if current version is specified in config file, like:
version = 0.4.3
```

**Comment by Lee-W** [comment]
@Woile Do you think we should use github actions to sync commitizen version to this repo?

**Comment by tiboun** [comment]
Hi there, any plan on updating the docker image ?

It's a great thing to have this docker image ready to use in CI, for instance gitlab-ci.

**Comment by woile** [comment]
This image was updated to the latest version. There is a cron daily checking for new pypi releases, and it will publish automatically if we release new versions of commitizen
