### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by pedrolsazevedo** [commitizen-tools/commitizen-docker-image#8]
Hello.
I've been trying to use the container, but only got the error:
`fatal: not a git repository (or any of the parent directories): .git`
![commitizen-docker](https://user-images.githubusercontent.com/7075064/198032498-0488e9f0-bbcc-4c8e-a439-5e9acab31b30.png)

Tried both ways:
- Passing the command through the container call:
```
docker run --rm -v $(pwd):/app -v ~/.gitconfig:/etc/gitconfig commitizen/commitizen:latest /bin/sh -c 'cz bump --yes --changelog'
```

- Creating a container and running the command on it:
```
docker run --rm -it -v $(pwd):/app --entrypoint /bin/sh commitizen/commitizen:latest
cz bump --yes --changelog
```
As shown in the screenshot, the .git folder is present.

Thanks.

**Comment by woile** [comment]
Could you run it with the `--debug` flag to se more details? thanks

**Comment by pedrolsazevedo** [comment]
Hello, sorry for taking so long to answer.

Here's the result of debug:
![commitizen-debug](https://user-images.githubusercontent.com/7075064/200826090-34b8ae38-e906-4942-9887-4b80f9fc94c0.png)

In this case, my problem was related to user permissions, after specifying the user on docker command I was able to run the commitizen smoothly.
![commitizen-idu](https://user-images.githubusercontent.com/7075064/200826426-a6a3a871-7dba-4950-a8af-bbbee3f8acca.png)

My final version of the command is:
```shell
docker run --rm -v $(pwd):/app -v ~/.gitconfig:/etc/gitconfig -u $(id -u) commitizen/commitizen:latest /bin/sh -c 'cz --debug bump --yes --changelog'
```
 
I was facing the same problem on my local machine and in Azure DevOps, but it's all working now.
Thanks.
