### ISSUE TITLE
Latest versioned docker image is getting overwritten daily

### ISSUE THREAD

**Issue by Tommyf** [commitizen-tools/commitizen-docker-image#9]
The latest docker image is getting published daily by the GitHub actions, even if there is no release.

While the underlying build of the image has not changed, it does not inspire confidence when you see that the image is constantly being updated.

Currently, https://hub.docker.com/r/commitizen/commitizen/tags is showing that the following tags were updated 12 hours ago (Nov 8th 2022), even though the last release was 12 days ago (Oct 28th 2022).
Tags:
- `latest`
- `2.37.0`
- `2`

The `2.35.0` tag shows as last updated on Oct 28th, even though it was released on Sep 12th as this is when the daily update stopped for that version. It's confusing for anyone looking and trying to verify the current image.

Tags for specific versions should be immutable - or at least you should not mutate them. Rolling tags are fine for latest, or major/minor specific tags, (e.g. `2`, `2.37`), the tags for specific versions should remain unchanged.

Even when rolling tags, they should only be updated when there is an actual underlying version change. By doing it daily, regardless of any changes, you introduce the problem that upstream problems could propagate into your images, that should not be changing.

For example, let's say your upstream image, `python:3-alpine`, changes. This is a rolling tag, so changes are expected. If this introduces a breaking change (It **should not**, but it **could**), then your images are now broken and any pipelines that depend on them may fail unexpectedly.

These problems can be super hard to track down - have done it many times :)

**Summary of issue:**

- Don't rebuild & push images daily, unless there is a new version released
- Don't allow specific version tags to be updated (Though I think in your case, this will be automatically fixed by the first point)

Note: I am not actually affected by this right now, just trying to help :). If needed, I can try to submit a PR for this later on if you need help trying to fix this.

**Comment by Lee-W** [comment]
Hi @Tommyf I totally agree with what you point out. It would be great if you could send us a PR!  Many thanks for reporting this issue!

**Comment by woile** [comment]
You are right, I think I forgot to exit != 0 here:
https://github.com/commitizen-tools/commitizen-docker-image/blob/master/scripts/auto_publish/compare-versions#L23

**Comment by woile** [comment]
Well I was wrong, the script is working fine. The problem is that docker has deprecated its v1 API. And it also requires an oauth token now 😢 
https://stackoverflow.com/a/39454426/2047185

**Comment by woile** [comment]
I've submitted a PR, please take a look. v2 doesn't require oauth so we are good

**Comment by Tommyf** [comment]
Oh that was quick! Nice one, thanks!

Currently it says the last push was 2 days ago, so I guess it's working :D
